name: Build Windows x64 Excel Extension


on:
  workflow_dispatch:


jobs:

  build:

    name: Build Excel Extension Windows x64

    runs-on: windows-2022


    steps:


    - name: Checkout duckdb-excel

      uses: actions/checkout@v4

      with:
        submodules: recursive



    - name: Prepare DuckDB source

      shell: pwsh

      run: |

        git clone --branch v1.5.4 --depth 50 https://github.com/duckdb/duckdb.git duckdb

        cd duckdb

        git submodule update --init --recursive

        cd ..



    - name: Setup MSVC

      uses: ilammy/msvc-dev-cmd@v1

      with:

        arch: x64



    - name: Setup vcpkg

      shell: pwsh

      run: |

        Write-Host "Checking vcpkg..."

        if (!(Test-Path "C:\vcpkg")) {

          git clone https://github.com/microsoft/vcpkg C:\vcpkg

          C:\vcpkg\bootstrap-vcpkg.bat

        }


        C:\vcpkg\vcpkg.exe --version



    - name: Install Excel dependencies

      shell: pwsh

      run: |

        C:\vcpkg\vcpkg.exe install



    - name: Install Ninja

      shell: pwsh

      run: |

        choco install ninja -y

        ninja --version



    - name: Build Excel extension

      shell: bash

      env:

        VCPKG_ROOT: C:/vcpkg


      run: |

        export GEN=ninja

        export DUCKDB_PLATFORM=windows_amd64

        export EXTENSION_NAME=excel

        export VCPKG_ROOT=C:/vcpkg

        export VCPKG=1

        export VCPKG_DEFAULT_TRIPLET=x64-windows

        echo "Building DuckDB Excel extension"

        make release



    - name: Check generated files

      shell: pwsh

      run: |

        Write-Host "Searching generated extension files..."


        Get-ChildItem `
          -Recurse `
          -Include "*.duckdb_extension","*.zip"



    - name: Upload Excel extension artifact

      uses: actions/upload-artifact@v4

      with:

        name: excel-v1.5.4-windows-amd64

        path: |

          **/*.duckdb_extension

          **/*.zip
