name: Build Windows x64 Excel Extension

on:
  workflow_dispatch:


jobs:

  build:

    name: Build Windows x64 Excel Extension

    runs-on: windows-2022


    steps:

    - name: Checkout extension
      uses: actions/checkout@v4


    - name: Checkout DuckDB v1.5.4

      shell: pwsh

      run: |

        git clone https://github.com/duckdb/duckdb.git duckdb

        cd duckdb

        git checkout v1.5.4



    - name: Setup MSVC

      uses: ilammy/msvc-dev-cmd@v1

      with:

        arch: x64



    - name: Install Ninja

      shell: pwsh

      run: |

        choco install ninja -y

        ninja --version



    #
    # Build directly
    #
    - name: Build extension

      shell: bash

      run: |


        export GEN=ninja

        export DUCKDB_PLATFORM=windows_amd64

        export EXTENSION_NAME=excel


        echo "Building DuckDB extension"

        make release



    - name: Show result

      shell: pwsh

      run: |

        Get-ChildItem `
          -Recurse `
          -Include "*.duckdb_extension","*.zip"
